apiVersion: apps/v1
kind: Deployment
metadata:
  name: yzlnrjdk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yzlnrjdk
  template:
    metadata:
      labels:
        app: yzlnrjdk
    spec:
      containers:
      - image: okteto.dev/yzlnrjdk:latest
        name: yzlnrjdk
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1ef75945-438b-480b-9df8-b0df199f86ea"
        - name: Vless_Path
          value: "/1ef75945-438b-480b-9df8-b0df199f86ea"
        - name: Vmess_UUID
          value: "6c41c480-6b60-4a36-b6c2-46c8d321bc59"
        - name: Vmess_Path
          value: "/6c41c480-6b60-4a36-b6c2-46c8d321bc59"
        - name: Share_Path
          value: "/v2link"
